import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    status: "false",
    userData: null
}

const authSLice = createSlice({
    name:"auth",
    initialState,
    reducers: {
        login: (state, action) => {
            state.status = true;
            state.userData = action.payload;
        },
        logout:(state) => {
            state.status = false;
            state.userData = null;
        }

    }
});

export const {login, logout} = authSLice.actions;

export default authSLice.reducer;



//Explanation

// This JavaScript code is using Redux Toolkit's createSlice function to generate a slice of the Redux store. A "slice" refers to a portion of the Redux state that is managed by a specific reducer function.

// The first line imports the createSlice function from Redux Toolkit. This function generates a reducer function for a specific slice of the state, along with actions and action creators.

// The initialState constant is an object that represents the initial state of this slice of the Redux store. It has two properties: status, which is initially set to "false", and userData, which is initially set to null.

// The authSlice constant is created by calling createSlice with an object as its argument. This object has three properties: name, initialState, and reducers.

// The name property is a string that identifies this slice of the state. It's used as a prefix for the action types that are generated by createSlice.
// The initialState property is the initial state for this slice of the state.
// The reducers property is an object that maps action types to reducer functions. In this case, there are two reducer functions: login and logout.
// The login reducer function takes the current state and an action as arguments. It sets state.status to true and state.userData to the payload of the action. The logout reducer function sets state.status to false and state.userData to null.

// The login and logout actions are then exported from this module using destructuring assignment. These are the action creators that were automatically generated by createSlice.

// Finally, the reducer function that was generated by createSlice is exported as the default export of this module. This is the authReducer that was imported in the previous code snippet.