import React from 'react'
import { UseDispatch } from 'react-redux'
import authService from '../../appwrite/auth'
import {logout} from '../../store/authSlice'

function LogoutBtn() {

    const dispatch = UseDispatch()

    const logoutHandler = () => {
        authService.logout().then(()=>{
            dispatch(logout())
        })
    }

    return (
        <button
    className='inline-bock px-6 py-2 duration-200 hover:bg-blue-100 rounded-full'
    onClick={logoutHandler}
    >Logout</button>
    )
}

export default LogoutBtn




// eXPLANATION

// This JavaScript code is a React component named LogoutBtn that renders a logout button and handles the logout process when the button is clicked.

// The first few lines import the necessary modules and functions. React is imported from the 'react' library, UseDispatch is imported from 'react-redux', authService is imported from a local file named 'auth.js' in the 'appwrite' directory, and logout is imported from a local file named 'authSlice.js' in the 'store' directory.

// UseDispatch is a hook from 'react-redux' that returns a reference to the dispatch function from the Redux store. This function is used to dispatch actions.

// authService is an object that provides methods for authentication, and logout is an action creator function that was generated by Redux Toolkit's createSlice function.

// Inside the LogoutBtn component, the UseDispatch hook is called to get the dispatch function from the Redux store. This function is stored in the dispatch constant.

// The logoutHandler function is defined next. This function calls the logout method of authService, which returns a promise. When this promise resolves, the logout action is dispatched to the Redux store. This will trigger the logout reducer function in 'authSlice.js', which sets status to false and userData to null.

// The component returns a button element with some CSS classes. The onClick prop of this button is set to the logoutHandler function, so this function will be called when the button is clicked.

// Finally, the LogoutBtn component is exported as the default export of this module, so it can be imported in other parts of the application.